import type { LevelDef } from './types';

export const LEVELS: LevelDef[] = [
  {
    number: 1,
    pyramidRows: 7,
    numColors: 2,
    targetColorIndex: 1,
    revertsOnExtra: false,
    hopDurationMs: 300,
    enemyTickMs: 1400,
    discs: [],
    enemyWaves: [{ type: 'red_ball', spawnAfterMs: 4000, count: 20, intervalMs: 4500 }],
  },
  {
    number: 2,
    pyramidRows: 7,
    numColors: 2,
    targetColorIndex: 1,
    revertsOnExtra: false,
    hopDurationMs: 280,
    enemyTickMs: 1300,
    discs: [{ row: 2, side: 'left' }],
    enemyWaves: [
      { type: 'red_ball', spawnAfterMs: 3000, count: 20, intervalMs: 4000 },
      { type: 'slick', spawnAfterMs: 8000, count: 10, intervalMs: 8000 },
    ],
  },
  {
    number: 3,
    pyramidRows: 7,
    numColors: 2,
    targetColorIndex: 1,
    revertsOnExtra: false,
    hopDurationMs: 280,
    enemyTickMs: 1200,
    discs: [
      { row: 2, side: 'right' },
      { row: 4, side: 'left' },
    ],
    enemyWaves: [
      { type: 'red_ball', spawnAfterMs: 3000, count: 15, intervalMs: 5000 },
      { type: 'coily_ball', spawnAfterMs: 5000, count: 5, intervalMs: 12000 },
    ],
  },
  {
    number: 4,
    pyramidRows: 7,
    numColors: 3,
    targetColorIndex: 2,
    revertsOnExtra: false,
    hopDurationMs: 260,
    enemyTickMs: 1100,
    discs: [
      { row: 2, side: 'left' },
      { row: 4, side: 'right' },
    ],
    enemyWaves: [
      { type: 'red_ball', spawnAfterMs: 3000, count: 15, intervalMs: 4500 },
      { type: 'coily_ball', spawnAfterMs: 6000, count: 5, intervalMs: 14000 },
    ],
  },
  {
    number: 5,
    pyramidRows: 7,
    numColors: 3,
    targetColorIndex: 2,
    revertsOnExtra: false,
    hopDurationMs: 260,
    enemyTickMs: 1000,
    discs: [
      { row: 3, side: 'left' },
      { row: 3, side: 'right' },
    ],
    enemyWaves: [
      { type: 'coily_ball', spawnAfterMs: 4000, count: 6, intervalMs: 12000 },
      { type: 'slick', spawnAfterMs: 6000, count: 10, intervalMs: 7000 },
      { type: 'sam', spawnAfterMs: 10000, count: 10, intervalMs: 8000 },
    ],
  },
  {
    number: 6,
    pyramidRows: 7,
    numColors: 4,
    targetColorIndex: 3,
    revertsOnExtra: false,
    hopDurationMs: 250,
    enemyTickMs: 1000,
    discs: [
      { row: 2, side: 'left' },
      { row: 4, side: 'right' },
      { row: 5, side: 'left' },
    ],
    enemyWaves: [
      { type: 'coily_ball', spawnAfterMs: 4000, count: 8, intervalMs: 10000 },
      { type: 'red_ball', spawnAfterMs: 3000, count: 20, intervalMs: 4000 },
    ],
  },
  {
    number: 7,
    pyramidRows: 7,
    numColors: 2,
    targetColorIndex: 1,
    revertsOnExtra: true,
    hopDurationMs: 250,
    enemyTickMs: 950,
    discs: [
      { row: 2, side: 'right' },
      { row: 5, side: 'left' },
    ],
    enemyWaves: [
      { type: 'coily_ball', spawnAfterMs: 4000, count: 8, intervalMs: 10000 },
      { type: 'slick', spawnAfterMs: 5000, count: 12, intervalMs: 6000 },
    ],
  },
  {
    number: 8,
    pyramidRows: 7,
    numColors: 3,
    targetColorIndex: 2,
    revertsOnExtra: true,
    hopDurationMs: 240,
    enemyTickMs: 900,
    discs: [
      { row: 3, side: 'left' },
      { row: 3, side: 'right' },
      { row: 5, side: 'left' },
    ],
    enemyWaves: [
      { type: 'coily_ball', spawnAfterMs: 3000, count: 10, intervalMs: 9000 },
      { type: 'red_ball', spawnAfterMs: 5000, count: 15, intervalMs: 4500 },
    ],
  },
  {
    number: 9,
    pyramidRows: 7,
    numColors: 4,
    targetColorIndex: 3,
    revertsOnExtra: true,
    hopDurationMs: 230,
    enemyTickMs: 850,
    discs: [
      { row: 2, side: 'left' },
      { row: 4, side: 'right' },
    ],
    enemyWaves: [
      { type: 'coily_ball', spawnAfterMs: 3000, count: 10, intervalMs: 8000 },
      { type: 'slick', spawnAfterMs: 4000, count: 15, intervalMs: 5000 },
      { type: 'sam', spawnAfterMs: 6000, count: 10, intervalMs: 6000 },
      { type: 'red_ball', spawnAfterMs: 5000, count: 15, intervalMs: 5000 },
    ],
  },
  {
    number: 10,
    pyramidRows: 7,
    numColors: 4,
    targetColorIndex: 3,
    revertsOnExtra: true,
    hopDurationMs: 220,
    enemyTickMs: 750,
    discs: [
      { row: 2, side: 'right' },
      { row: 5, side: 'left' },
    ],
    enemyWaves: [
      { type: 'coily_ball', spawnAfterMs: 2000, count: 15, intervalMs: 7000 },
      { type: 'slick', spawnAfterMs: 3000, count: 20, intervalMs: 4000 },
      { type: 'sam', spawnAfterMs: 4000, count: 15, intervalMs: 5000 },
      { type: 'red_ball', spawnAfterMs: 2000, count: 25, intervalMs: 3500 },
    ],
  },
];
